### ISSUE TITLE
Wrong connection string key for SendGrid

### ISSUE THREAD

**Issue by gius** [ohadschn/letsencrypt-webapp-renewer#11]
According to the readme, under section **Notifications**, SendGrid should be configured via "`letsencrypt:webAppName-SendGridApiKey` Application Setting".

The readme should be updated as the actual configuration is through a _connection string_ with key `letsencrypt:SendGridApiKey`

**Comment by ohadschn** [comment]
Good catch, thanks!

**Comment by optiks** [comment]
This is super confusing; why is it a connection string?

**Comment by ohadschn** [comment]
@optiks because it's basically a connection string to SendGrid. It's a secret that shouldn't be exposed, and connection strings are better protected than plain application settings.

**Comment by optiks** [comment]
Better protected in what way?

Within the portal both connection strings and app settings are encrypted at rest. Both are ultimately stored in environment variables. Both have their values hidden by default.

I’d just suggest having a fallback that *if* the app setting is defined, that it’s used. I wasted a little while trying to work out why it wasn’t emailing. (There was no logging to say that the value should have been configured as a connection string instead of an app setting.)

**Comment by ohadschn** [comment]
> Better protected in what way?
> 
> Within the portal both connection strings and app settings are encrypted at rest. Both are ultimately stored in environment variables. Both have their values hidden by default.

That's fair, and I stand corrected, but going by this logic one wouldn't use connection strings for anything, ever. Conceptually, I still see a secret key more as a connection string than as an application setting.

> I’d just suggest having a fallback that _if_ the app setting is defined, that it’s used. I wasted a little while trying to work out why it wasn’t emailing. (There was no logging to say that the value should have been configured as a connection string instead of an app setting.)

Can you share those logs? You should have seen a clear warning telling you to set the key as a connection string: https://github.com/ohadschn/letsencrypt-webapp-renewer/blob/ecbda6b26da4f7c92288e4abbfad34206eadfefe/OhadSoft.AzureLetsEncrypt.Renewal/OhadSoft.AzureLetsEncrypt.Renewal.WebJob/Email/SendGridNotifier.cs#L40
