### ISSUE TITLE
SendGrid email hosts field

### ISSUE THREAD

**Issue by timothyleerussell** [ohadschn/letsencrypt-webapp-renewer#68]
When the hosts field is an array of strings rather than a single value, the SendGrid email does not enumerate them but instead lists the hosts as:

`Hosts: System.String[]`

Not a big deal but I thought I would flag it.

Great extension! Thanks so much.

**Comment by ohadschn** [comment]
Thank you, I fixed it here but didn't get a chance to put out a new release since then: https://github.com/ohadschn/letsencrypt-webapp-renewer/commit/f903626d0d5c33089598cc6af12b1ad19bfdfebf
You can build from source if you'd like the fix (maybe you can even take a binary from the CI, not sure how permissions work).

**Comment by timothyleerussell** [comment]
Thanks Ohad!

Timothy
