### ISSUE TITLE
Adding New Hosts

### ISSUE THREAD

**Issue by spotonconnect** [ohadschn/letsencrypt-webapp-renewer#7]
In our web app we can host multiple sites (hosts) and we routinely add new hosts. Can we re-run the command when adding new hosts?

If so, when adding a new host do we need to include the previous hosts or just the new hosts in the list of host names?
Hosts is a semicolon-delimited list of host names

**Comment by ohadschn** [comment]
You could re-run the WebJob as many times you'd like, using all hosts or just the new ones (but remember to restore the full list after you're done so the next renewal doesn't miss any). 

Just be sure you don't go past the Let's Encrypt rate limits: https://letsencrypt.org/docs/rate-limits/.

**Comment by ohadschn** [comment]
Actually I might have misunderstood here, so I'll clarify my answer:
1. When adding **new web apps**, you can just re-run the command/WebJob with all the web apps - it will simply regenerate the cert for all of them, including the existing ones (which may not have needed renewal, but no harm done)
1. When adding **new hosts to an existing web app**, you *must include the full list of hosts*, because the single generated multi-domain (SAN) cert must match all the hosts you want enabled for your site.

Anyway, closing this, feel free to re-open if you question wasn't answered.
