### ISSUE TITLE
Support DNS challenge

### ISSUE THREAD

**Issue by ohadschn** [ohadschn/letsencrypt-webapp-renewer#91]
Since DNS challenge support was dropped from `letsencrypt.azure.core`, new support must be implemented on top of https://github.com/sjkp/letsencrypt-azure.

Waiting for instructions here: https://github.com/sjkp/letsencrypt-siteextension/pull/332#event-2693400466.

**Comment by rasolo** [comment]
Hi @ohadschn,

I get the error "Azure DNS challenge currently not supported" when using https://github.com/ohadschn/letsencrypt-webapp-renewer, is there a different method that can be used?

I don't understand this sentence in the readme: "You may use the ACME DNS challenge instead of the HTTP challenge. Currently only Azure DNS is supported, and it can be activated using the following configuration:" It says that you can use the ACME DNS challenge, then it says only Azure DNS challenge is supported thereby stating that the previous statement is false. And the DNS challenge which i'm guessing is the Azure DNS challenge doesn't work either..

Anyway, is there a way to get it working using some other method?

Thanks

**Comment by ohadschn** [comment]
Hi, I'm afraid it's not currently supported since the underlying package I was using (`letsencrypt.azure.core`) dropped support with the move to ACME v2 (so you can't just use an older version since v1 has been deprecated by Let's Encrypt).

I started working on support using the new package (`LetsEncrypt.Azure.Core.V2`), you can check it out here: https://github.com/ohadschn/letsencrypt-webapp-renewer/tree/azure-dns.

**Comment by ohadschn** [comment]
Fixed in [1.0.5](https://github.com/ohadschn/letsencrypt-webapp-renewer/releases/tag/1.0.5)
